/* Generated by tools/gen_sprites.py from the PNG sheets in assets/ — do not edit.
 * Regenerate rather than patching: the PNGs are the source of truth.
 */

#pragma once

#include "lvgl.h"

#define ZOO_FRAME_W 48
#define ZOO_FRAME_H 48
#define ZOO_FRAMES 12
#define ZOO_ANIMAL_COUNT 4

typedef struct {
    const char *name;
    /* Both levels const, so the table of frame pointers lives in flash. Without
     * the second const the array is one of *mutable* pointers and the linker
     * must put all 192 bytes of it in DRAM — confirmed in the map file before
     * this was fixed. lv_animimg_set_src() only reads its argument, so the cast
     * at the call site is sound. */
    const void *const *frames;
} zoo_animal_t;

extern const zoo_animal_t zoo_animals[ZOO_ANIMAL_COUNT];
