"""Turn the zoo sprite sheets into an LVGL image table.

Run from the repo root after editing anything in assets/:

    python3 tools/gen_sprites.py

Needs Pillow >= 12, which lives in the system python rather than the IDF
virtualenv — this is a build-time authoring tool, not something the firmware
build calls, so it is run by hand and its output is committed.

The version floor is real: frame_bytes() uses get_flattened_data(), which
replaced getdata() in Pillow 12 and does not exist before it. On an older
Pillow this dies with AttributeError on the first frame, and because the
generated C is committed, nothing else in the tree would notice.

Output is RGB565A8: a plane of RGB565 pixels followed by a plane of 8-bit alpha.
Chosen over the more obvious indexed format even though the art has under ten
colours and would fit a 16-entry palette at a quarter of the size. LVGL 9's
decoder hands a variable RGB565A8 image straight to the renderer as a pointer
into flash, while an indexed one is expanded to ARGB8888 in RAM first — and with
LV_CACHE_DEF_SIZE=0 that expansion is redone on every single frame, 9.2 kB at a
time out of a 16 kB LVGL heap. The indexed version trades flash we have three
megabytes spare of for RAM we have kilobytes spare of.

The delivered zoo_sprites.h keyed transparency to magenta, which LVGL 8 could do
and LVGL 9 cannot: chroma-keying was removed and there is no replacement. The
PNGs carry a real alpha channel, so that information was never lost — this reads
it from the source rather than trying to recover it from the key.
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT_C = ROOT / "main" / "zoo_sprites.c"
OUT_H = ROOT / "main" / "zoo_sprites.h"

# Sheet layout. Frames read left to right, then top to bottom.
FRAME_W = 48
FRAME_H = 48
FRAMES = 12

# Order is the order they appear on screen, so it is deliberate rather than
# whatever the directory listing happens to give.
ANIMALS = ["elephant", "giraffe", "lion", "monkey"]

def sheet_path(animal: str) -> Path:
    return ASSETS / f"{animal}_{FRAME_W}x{FRAME_H}_{FRAMES}f.png"


def rgb565(r: int, g: int, b: int) -> int:
    """Same packing as RGB565() in main/display.h, but not the same product:
    that macro yields a host-order uint16_t for the raw fill path, this yields
    the bytes LVGL wants. Kept separate because they sit either side of a
    language boundary, not because the formula is in dispute."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def frame_bytes(sheet: Image.Image, index: int) -> bytes:
    """One frame as RGB565A8: colour plane, then alpha plane.

    The two planes are separate rather than interleaved because that is what the
    renderer expects — it reads the alpha as a mask starting at data + stride*h
    (see lv_draw_sw_img.c). Interleaving would be a plausible-looking guess that
    renders as noise.
    """
    cols = sheet.width // FRAME_W
    x0 = (index % cols) * FRAME_W
    y0 = (index // cols) * FRAME_H
    frame = sheet.crop((x0, y0, x0 + FRAME_W, y0 + FRAME_H))

    color = bytearray()
    alpha = bytearray()
    for r, g, b, a in frame.get_flattened_data():
        # Little-endian halfwords: the panel wants big-endian, but the byte swap
        # happens in the flush path (PANEL_SWAP_BYTES), so image data stays in
        # LVGL's native order. Pre-swapping here would swap it twice.
        color += rgb565(r, g, b).to_bytes(2, "little")
        # Binarised. The art is on/off — all four sheets decode to exactly two
        # alpha levels and no partial pixels — and a future sheet with soft
        # edges should become a hard edge rather than whatever truncation gives.
        alpha.append(255 if a else 0)

    return bytes(color + alpha)


def c_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {row},")
    return "\n".join(lines)


def main() -> int:
    missing = [a for a in ANIMALS if not sheet_path(a).exists()]
    if missing:
        print(f"missing sheets in {ASSETS}: {', '.join(missing)}", file=sys.stderr)
        return 1

    c = [
        "/* Generated by tools/gen_sprites.py from the PNG sheets in assets/ — do not edit.",
        " * Regenerate rather than patching: the PNGs are the source of truth.",
        " */",
        "",
        '#include "zoo_sprites.h"',
        "",
    ]

    total = 0
    for animal in ANIMALS:
        path = sheet_path(animal)
        sheet = Image.open(path).convert("RGBA")
        if sheet.width * sheet.height != FRAME_W * FRAME_H * FRAMES:
            print(f"{path.name}: {sheet.width}x{sheet.height} is not {FRAMES} "
                  f"frames of {FRAME_W}x{FRAME_H}", file=sys.stderr)
            return 1

        for i in range(FRAMES):
            data = frame_bytes(sheet, i)
            total += len(data)
            c += [
                f"static const uint8_t {animal}_{i}_map[] = {{",
                c_array(data),
                "};",
                "",
                f"static const lv_image_dsc_t {animal}_{i} = {{",
                "    .header = {",
                "        .magic  = LV_IMAGE_HEADER_MAGIC,",
                "        .cf     = LV_COLOR_FORMAT_RGB565A8,",
                f"        .w      = {FRAME_W},",
                f"        .h      = {FRAME_H},",
                f"        .stride = {FRAME_W * 2},",
                "    },",
                f"    .data_size = sizeof({animal}_{i}_map),",
                f"    .data = {animal}_{i}_map,",
                "};",
                "",
            ]

        srcs = ", ".join(f"&{animal}_{i}" for i in range(FRAMES))
        c += [
            f"static const void *const {animal}_frames[ZOO_FRAMES] = {{{srcs}}};",
            "",
        ]

    entries = ",\n".join(
        f'    {{ .name = "{a}", .frames = {a}_frames }}' for a in ANIMALS
    )
    c += [
        "const zoo_animal_t zoo_animals[ZOO_ANIMAL_COUNT] = {",
        entries + ",",
        "};",
        "",
    ]

    h = f"""/* Generated by tools/gen_sprites.py from the PNG sheets in assets/ — do not edit.
 * Regenerate rather than patching: the PNGs are the source of truth.
 */

#pragma once

#include "lvgl.h"

#define ZOO_FRAME_W {FRAME_W}
#define ZOO_FRAME_H {FRAME_H}
#define ZOO_FRAMES {FRAMES}
#define ZOO_ANIMAL_COUNT {len(ANIMALS)}

typedef struct {{
    const char *name;
    /* Both levels const, so the table of frame pointers lives in flash. Without
     * the second const the array is one of *mutable* pointers and the linker
     * must put all 192 bytes of it in DRAM — confirmed in the map file before
     * this was fixed. lv_animimg_set_src() only reads its argument, so the cast
     * at the call site is sound. */
    const void *const *frames;
}} zoo_animal_t;

extern const zoo_animal_t zoo_animals[ZOO_ANIMAL_COUNT];
"""

    OUT_C.write_text("\n".join(c))
    OUT_H.write_text(h)
    print(f"{OUT_C.relative_to(ROOT)}: {len(ANIMALS)} animals, "
          f"{len(ANIMALS) * FRAMES} frames, {total / 1024:.1f} kB of pixels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
